tweak

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,7 +1,23 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-echo "----->  Starting Indexd Custom Buildpack Compile"
+# fail fast
+set -e
 
+# debug
+# set -x
+
+# clean up leaking environment
+unset GIT_DIR
+
+
+BUILD_DIR=$1
+CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+
+S3_BUCKET="heroku.build.intersect.com"
+
+echo "----- Starting INDEXD BUILD"
 function mktmpdir() {
   dir=$(mktemp -t indexd-$1-XXXX)
   rm -rf $dir
@@ -17,12 +33,6 @@ function package_download() {
   package="http://${S3_BUCKET}.s3.amazonaws.com/${engine}.tgz"
   curl $package -s -o - | tar xzf - -C $location
 }
-
-BUILD_DIR=$1
-CACHE_DIR=$2
-LP_DIR=`cd $(dirname $0); cd ..; pwd`
-
-S3_BUCKET="heroku.build.intersect.com"
 
 # vendor directories
 VENDORED_AUTOMAKE="$(mktmpdir automake)"
